### ISSUE TITLE
How do I change fonts?

### ISSUE THREAD

**Issue by PyGamer0** [dfrg/swash_demo#1]

**Comment by dfrg** [comment]
If you want to add custom fonts, you can change the line here: https://github.com/dfrg/swash_demo/blob/master/src/main.rs#L43
to something like:
```
    let fonts = layout::FontLibrary::builder()
        .add_system_fonts()
        .add_dir("/path/to/custom/fonts")
        .build();
```
And that will add all fonts from the specified path to the library. 

You can select the fonts by family name using the code here: https://github.com/dfrg/swash_demo/blob/master/src/main.rs#L513

This is all a bit fragile because it's really just a proof of concept, but the above should get you started. I'm currently working on a real text layout solution in the parley repo that should be in a reasonably usable state in roughly 6 weeks.

**Comment by PyGamer0** [comment]
thanks
